openapi: "3.0.0"
info:
  version: 1.0.0
  title: Drawing Interpretation Service
  description: An API that allows user to view and submit interpretations about abstract drawings
  contact:
    name: Chris Chapman
    email: chrischapman900@gmail.com
    url: http://chrischapman.co
servers:
  - url: http://localhost:5000
paths:
  /drawings:
    get:
      summary: List all drawings
      operationId: list_drawings
      tags:
        - drawing
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: A paged array of drawings
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Drawings"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /drawings/{drawing_id}:
    parameters:
      - name: drawing_id
        in: path
        required: true
        description: The id of the drawing to retrieve
        schema:
          type: string
    get:
      summary: Get a specific drawing
      operationId: showDrawingById
      tags:
        - drawing
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Drawing"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /drawings/{drawing_id}/interpretations:
    parameters:
      - name: drawing_id
        in: path
        required: true
        description: The id of the drawing to retrieve
        schema:
          type: string
    get:
      summary: Get a all interpretations for a specific drawing
      operationId: showDrawingInterpretations
      tags:
        - interpretation
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Interpretations"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      summary: Submit an interpretation
      operationId: createInterpretation
      tags:
        - interpretation
      requestBody:
        description: Interpretation to add to the drawing
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Interpretation'
      responses:
        '201':
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    User:
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        username:
          type: string
    Drawing:
      required:
      - id
      - image_url
      - description
      properties:
        id:
          type: integer
          format: int64
        image_url:
          type: string
          example: https://www.example.com/image.png
        description:
          type: string
          example: vertical triangle with a rectangle below
        interpretations:
          type: array
          items:
            $ref: "#/components/schemas/Interpretations"
    Drawings:
      type: array
      items:
        $ref: "#/components/schemas/Drawing"
    Interpretation:
      required:
      - id
      - user_id
      - drawing_id
      - text
      properties:
        id:
          type: integer
          format: int64
        user_id:
          $ref: "#/components/schemas/User"
        drawing_id:
          $ref: "#/components/schemas/Drawing"
        text:
          type: string
          example: Rocketship
    Interpretations:
      type: array
      items:
        $ref: "#/components/schemas/Interpretation"
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string